### ISSUE TITLE
Spaces and Special characters in git folder names and file fails 'just discover-persist-gitlab-project-repo-assets-content [group id]'

### ISSUE THREAD

**Issue by dittybijil** [netspective-studios/gitlab-enhanced#2]
For mirroring a bare repo content into database we tried 
`just discover-persist-gitlab-project-repo-assets-content [gitlab_group_id]`  triggers a validation error.

While checking we found some spaces in folder names and file names and some special characters like `@ (  etc` . After removing these it worked.  

Can you please check this issue
@shah

**Comment by shah** [comment]
This has been fixed please verify and let me know of any other related issues.
